### ISSUE TITLE
NPE when there is some class missing at compile time

### ISSUE THREAD

**Issue by fpetrola** [dragome/dragome-sdk#148]
``` java
Compiling classes: ...................................................................

Exception in thread "Thread-13" java.lang.RuntimeException: java.lang.NullPointerException
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:170)
	at com.dragome.web.helpers.serverside.DragomeCompilerLauncher.compileWithMainClass(DragomeCompilerLauncher.java:71)
	at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.compile(DirectoryWatcher.java:263)
	at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.startWatching(DirectoryWatcher.java:249)
	at com.dragome.web.serverside.servlets.CompilerServlet$1.run(CompilerServlet.java:92)

Caused by: java.lang.NullPointerException
	at com.dragome.compiler.Project.visitSuperTypes(Project.java:302)
	at com.dragome.compiler.Project.visitSuperTypes(Project.java:305)
	at com.dragome.compiler.Project.resolve(Project.java:481)
	at com.dragome.compiler.writer.Assembly.resolveNoTainting(Assembly.java:340)
	at com.dragome.compiler.DragomeJsCompiler.execute(DragomeJsCompiler.java:259)
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:165)
	... 4 more

```

**Comment by xpenatan** [comment]
This will be really useful to detect class that is trying to compile that should or not be there.

**Comment by nicolaichuk** [comment]
+1

**Comment by mirkosertic** [comment]
I am also encountering this issue with latest 0.96-beta4. It seems to happejn while parsing the supertypes of 
com.dragome.web.serverside.servlets.GetPostServlet.
