### ISSUE TITLE
Wildfly, ClassCastException on start application

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#48]
2015-06-16 18:22:53,828 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-9) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./AAA: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./AAA: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_25]
Caused by: java.lang.ClassCastException: org.jboss.modules.ModuleClassLoader cannot be cast to java.net.URLClassLoader
	at com.dragome.serverside.servlets.CompilerServlet.compile(CompilerServlet.java:55)
	at com.dragome.serverside.servlets.CompilerServlet.init(CompilerServlet.java:42)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:220)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:125)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:87)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:71)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	... 3 more

**Comment by fpetrola** [comment]
Hi, since org.jboss.modules.ModuleClassLoader is not URClassloader classpath items must be obtained using other mechanism, as it's suggested here: http://markmail.org/message/ohcanda7ait7i3gl may be we can use ClassLoader.getResources("/") to get them. I'll be making some research to fix it quickly.

**Comment by fpetrola** [comment]
I've made some research about it, but I cannot find a way to obtain URL list from a non URLClassLoader. Using getResources only returns "..../classes" folder but not jars items.

**Comment by fpetrola** [comment]
While we find out a way to get classpath items from non URLClassLoader you can use maven-dragome-plugin for offline compiling: https://github.com/dragome/dragome-sdk/tree/master/dragome-maven-plugins
