### ISSUE TITLE
Error compile java to javascript

### ISSUE THREAD

**Issue by caffeine-mgn** [dragome/dragome-sdk#50]
I fix problems in my test project from issue #49 and run:
$ mvn clean compile package jetty:run
jetty running with message:
Exception in thread "Thread-12" java.lang.RuntimeException: java.lang.RuntimeException: Could not find com/dragome/html/dom/html5canvas/CanvasImageSource.class on class path
        at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:195)
        at com.dragome.web.helpers.serverside.DragomeCompilerLauncher.compileWithMainClass(DragomeCompilerLauncher.java:44)
        at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.compile(DirectoryWatcher.java:261)
        at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.main(DirectoryWatcher.java:247)
        at com.dragome.web.serverside.servlets.CompilerServlet$1.run(CompilerServlet.java:83)
Caused by: java.lang.RuntimeException: Could not find com/dragome/html/dom/html5canvas/CanvasImageSource.class on class path
        at com.dragome.compiler.utils.FileManager.getFileForInput(FileManager.java:110)
        at com.dragome.compiler.units.ClassUnit.getClassFile(ClassUnit.java:683)
        at com.dragome.compiler.units.ClassUnit.getLastModified(ClassUnit.java:65)
        at com.dragome.compiler.units.ClassUnit.isUpToDate(ClassUnit.java:134)
        at com.dragome.compiler.type.TypeResolver.visit(TypeResolver.java:39)
        at com.dragome.compiler.Project.visitSuperTypes(Project.java:295)
        at com.dragome.compiler.Project.resolve(Project.java:464)
        at com.dragome.compiler.writer.Assembly.resolveNoTainting(Assembly.java:338)
        at com.dragome.compiler.DragomeJsCompiler.execute(DragomeJsCompiler.java:276)
        at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:190)
        ... 4 more

**Comment by caffeine-mgn** [comment]
I remind you that I made git clone dragome and install it to local maven

**Comment by fpetrola** [comment]
I think it might be a bug around jsdelegate bytecode generator. Try deleting /tmp/jsdelegate directory and run it again.

**Comment by caffeine-mgn** [comment]
I tried it. Does not work :(

**Comment by fpetrola** [comment]
If you are trying to execute archetype you need to update it from repo to reflect moving classes refactoring.

**Comment by fpetrola** [comment]
Fixed in new release 0.96-beta2
